import requests
import streamlit as st
from PIL import Image


def show_client_view(backend_url: str, user_id: int):
    """Render the plant image upload and diagnostic history tabs for standard clients."""
    st.title("🌿 Client Plant Diagnostics Hub")
    st.write(
        "Upload an image of your plant below. Our YOLOv11s model will identify the taxonomy species."
    )

    tab1, tab2 = st.tabs(["⚡ Run Inference", "📜 Diagnostics History Logs"])

    with tab1:
        uploaded_file = st.file_uploader(
            "Choose a plant image asset...", type=["jpg", "jpeg", "png"]
        )
        if uploaded_file is not None:
            st.image(
                uploaded_file,
                caption="Target Asset Target Input Sample",
                width=350,
            )

            if st.button("Analyze System Payload", type="primary"):
                with st.spinner("Executing model processing array..."):
                    try:
                        files = {
                            "file": (
                                uploaded_file.name,
                                uploaded_file.getvalue(),
                                uploaded_file.type,
                            )
                        }
                        data = {"user_id": user_id}

                        response = requests.post(
                            f"{backend_url}/api/predict",
                            files=files,
                            data=data,
                        )

                        if response.status_code == 200:
                            result = response.json()
                            st.success("Analysis Complete!")

                            c1, c2 = st.columns(2)
                            c1.metric(
                                "Predicted Species", result["predicted_species"]
                            )
                            c2.metric(
                                "Confidence Score",
                                f"{result['confidence'] * 100:.2f}%",
                            )
                        else:
                            st.error(
                                "Error communicating with inference engine pipeline layout."
                            )
                    except Exception as e:
                        st.error(
                            f"Network processing exception framework alert: {e}"
                        )

    with tab2:
        st.subheader("Your Personal Diagnosis History")
        try:
            response = requests.get(f"{backend_url}/api/history/{user_id}")
            if response.status_code == 200:
                logs = response.json()
                if not logs:
                    st.info("No logs generated by this account yet.")
                else:
                    for log in reversed(logs):
                        status_chip = "⏳ Pending Review"
                        if log["is_verified"] == 1:
                            status_chip = "✅ Verified by Expert"
                        elif log["is_verified"] == -1:
                            status_chip = (
                                f"⚠️ Adjusted to: {log['corrected_species']}"
                            )

                        with st.expander(
                            f"Diagnosis Log #{log['id']} — {log['predicted_species']} ({log['confidence']*100:.1f}%)"
                        ):
                            st.write(f"**Date:** {log['timestamp']}")
                            st.write(f"**Status:** {status_chip}")
                            st.image(log["image_path"], width=200)
        except Exception as e:
            st.error(f"Could not retrieve history logs: {e}")